source = ~/.config/hypr/config/defaults.conf

# Autostart wiki https://wiki.hyprland.org/Configuring/Keywords/#executing

# Slow app launch fix
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment
exec-once = hash dbus-update-activation-environment 2>/dev/null
exec-once = dbus-update-activation-environment --systemd

# Systemd services
exec-once = systemctl --user start hyprpolkitagent
exec-once = systemctl --user start makop
exec-once = systemctl --user start wob.socket wob

# Theme and background
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark' && gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = swaybg -o \* -i $HOME/Pictures/wallpapers/orange-mountain.png -m fill &
exec-once = hyprlock
exec-once = waybar &
exec-once = pactl set-source-mute @DEFAULT_SOURCE@ true # Mute mic at startup

# Autostart apps
exec-once = bitwarden-desktop &
exec-once = sleep 10 && steam &
exec-once = discord --start-minimized --enable-features=UseOzonePlatform --ozone-platform=wayland &
exec-once = spotify-launcher &
exec-once = solaar --window hide &
exec-once = udiskie -s &

# ## Idle configuration
# exec-once = uwsm app -- $idlehandler
