hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment")
    hl.exec_cmd("hash dbus-update-activation-environment 2>/dev/null")
    hl.exec_cmd("dbus-update-activation-environment --systemd")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("systemctl --user start makop")
    hl.exec_cmd("systemctl --user start wob.socket wob")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark' && gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")
    hl.exec_cmd("swaybg -o \\* -i $HOME/Pictures/wallpapers/orange-mountain.png -m fill")
    hl.exec_cmd("hyprlock")
    hl.exec_cmd("waybar")
    hl.exec_cmd("pactl set-source-mute @DEFAULT_SOURCE@ true")
    hl.exec_cmd("bitwarden-desktop")
    hl.exec_cmd("sleep 10 && steam")
    hl.exec_cmd("discord --start-minimized --enable-features=UseOzonePlatform --ozone-platform=wayland")
    hl.exec_cmd("spotify-launcher")
    hl.exec_cmd("solaar --window hide")
    hl.exec_cmd("udiskie")
end)
