local cmd = hl.exec_cmd
local defaults = require("config/defaults")

hl.on("hyprland.start", function()
    cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    cmd("systemctl --user import-environment")
    cmd("hash dbus-update-activation-environment 2>/dev/null")
    cmd("dbus-update-activation-environment --systemd")
    cmd("systemctl --user start hyprpolkitagent")
    cmd("systemctl --user start makop")
    cmd("systemctl --user start wob.socket wob")
    cmd("gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark' && gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")
    cmd("swaybg -o \\* -i $HOME/Pictures/wallpapers/orange-mountain.png -m fill")
    cmd("hyprlock")
    cmd("pactl set-source-mute @DEFAULT_SOURCE@ true")
    cmd("bitwarden-desktop")
    cmd("sleep 10 && steam")
    cmd("solaar --window hide")
    cmd("udiskie")
    cmd("spotify-launcher")
    cmd(defaults.chatapps)
    cmd(defaults.homeassistant)
    cmd("waybar")
end)
