# General
$filemanager = thunar
$applauncher = rofi -show drun -sorting-method "fzf"

$terminal = kitty
$browser = brave
$chatapps = discord --enable-features=UseOzonePlatform --ozone-platform=wayland & Telegram & firefoxpwa site launch $(firefoxpwa profile list | grep -i messenger | awk -F'[()]' '{print $2}')
$homeassistant = firefoxpwa site launch $(firefoxpwa profile list | grep -i "home assistant" | awk -F'[()]' '{print $2}')
$ide = code
$idlehandler = swayidle -w timeout 300 'swaylock -f -c 000000' before-sleep 'swaylock -f -c 000000'
$passwordmanager = bitwarden-desktop

# Monitor Brightness
$brightnessScript = $HOME/.config/hypr/scripts/brightness_set.sh

# Screenshots
$shotregion = hyprshot -m region --clipboard-only --freeze --silent
$shotwindow = hyprshot -m window --clipboard-only --freeze --silent

# Wayland Overlay Bar
$wobSocket = $XDG_RUNTIME_DIR/wob.sock