- name: Stow dotfiles
  include_tasks: tasks/stow_dotfiles.yaml
  vars:
    target_path: $HOME
    become_bool: false
    package: hyprland

- name: Stow wallpapers
  include_tasks: tasks/stow_dotfiles.yaml
  vars:
    target_path: $HOME/Pictures
    become_bool: false
    package: wallpapers

- name: Install essential packages
  include_tasks: tasks/install_official.yaml
  loop:
  - hyprland
  - uwsm
  - xdg-desktop-portal-hyprland
  - xdg-desktop-portal-gtk
  - hyprpolkitagent
  - gnome-themes-extra
  - qt5-wayland
  - qt6-wayland
  - swaybg
  - otf-commit-mono-nerd
  - hyprlock
  loop_control:
    loop_var: package

- name: Create getty override directory for TTY1 autologin
  ansible.builtin.file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Configure TTY1 autologin
  ansible.builtin.copy:
    dest: /etc/systemd/system/getty@tty1.service.d/autologin.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      [Service]
      ExecStart=
      ExecStart=-/usr/bin/agetty --autologin {{ target_user }} --skip-login --noissue %I $TERM
      TTYVTDisallocate=no
  become: true
  
- name: Reload systemd
  ansible.builtin.command: systemctl daemon-reexec
  become: true

- name: Ensure system boots to graphical target
  ansible.builtin.systemd:
    name: graphical.target
    enabled: true
  become: true

- name: Enable lingering for user services
  ansible.builtin.command:
    cmd: loginctl enable-linger {{ target_user }}
  changed_when: false
  become: true