- name: Copy dotfiles
  ansible.builtin.copy:
    src: ../dotfiles/sddm/sddm.conf.d
    dest: /etc
  become: true

- name: Install essential packages
  include_tasks: tasks/install_official.yaml
  loop:
  - sddm
  - layer-shell-qt
  - qt6-svg
  - qt6-multimedia-ffmpeg
  loop_control:
    loop_var: package

- name: Enable systemd service
  ansible.builtin.systemd_service:
    name: sddm
    enabled: true
  become: true