- name: Install dotfiles for {{ package }} at {{ target_path }}
  ansible.builtin.shell:
    cmd: |
      cd ../dotfiles
      find {{ target_path }}/ -maxdepth 1 -name "$(ls -d {{ package }}/*)" -exec rm -rf {} +
      stow -t {{ target_path }} --verbose=2 {{ package }}
  when: become_bool
  become: "{{ become_bool }}"

- name: Install dotfiles for {{ package }} at {{ target_path }}
  ansible.builtin.shell:
    cmd: |
      cd ../dotfiles
      find {{ target_path }}/ -maxdepth 1 -name "$(ls -d {{ package }}/*)" -exec rm -rf {} +
      stow -t {{ target_path }} --verbose=2 {{ package }}
  when: not become_bool 