- name: Stow dotfiles
  include_tasks: tasks/stow_dotfiles.yaml
  vars:
    target_path: $HOME
    become_bool: false
    package: kitty

- name: Install essential packages
  include_tasks: tasks/install_official.yaml
  vars:
    package: kitty